"""
K Manga (Kodansha) API client — chapter tracking only.

API base:  https://api.kmanga.kodansha.com
Auth:      Session cookies (birthday + uwt) obtained via POST /web/user/login.
           Every request requires an x-kmanga-hash header generated by signing
           the full request parameter dict with the birthday cookie value.
           Geographic restriction: US IPs only (403 otherwise).

Title IDs: The integer in the K Manga URL:
           https://kmanga.kodansha.com/title/{title_id}

x-kmanga-hash algorithm (reverse-engineered from py-kapi/pykapi/kapi.py):
  For each param key sorted alphabetically:
    part = SHA256(key) + "_" + SHA512(str(value))
  joined = ",".join(all parts)
  param_digest = SHA256(joined)
  birthday_dict = JSON.parse(birthday_cookie)
  birthday_hash = SHA256(birthday_dict["value"]) + "_" + SHA512(birthday_dict["expires"])
  final_hash = SHA512(param_digest + birthday_hash)

Chapter detection — two API tiers:

  PRIMARY (no auth required):
    GET /web/title/detail?title_id=N
      → Returns "web_title" object with:
        episode_id_list     — ONE entry per CHAPTER (compiled chapter, not sub-episode)
        total_episode_count — The true chapter count (e.g. 68)
      Use episode_id_list[-1] to get the latest chapter's episode ID, then call
      /web/episode to get the episode_name and parse the chapter number.
      Only the default birthday cookie is needed — no login required.

  FALLBACK (requires auth):
    GET /title/list?title_id_list=N
      → Returns ALL raw episodes (e.g. 195 sub-episodes for 68 chapters).
        episode_id_list[-1] here points to a sub-episode, not a chapter.
        total_episode_count here counts sub-episodes, NOT chapters.
      Used as a fallback for titles behind a paywall or not publicly listed.

  Key insight: /web/title/detail is the correct endpoint.  /title/list returns
  sub-episode granularity which is inappropriate for chapter tracking.

Session management:
  - On first use (or when uwt cookie is absent), call login() to authenticate.
  - Cookies (birthday + uwt) are returned from login() as a dict for the caller
    to persist in the settings DB.
  - Pass persisted cookies back into the constructor on subsequent app starts
    to avoid re-logging in on every poll.
  - If a request fails with KMangaAuthError, caller should re-login.
"""
import hashlib
import json
import logging
import re

import httpx

logger = logging.getLogger(__name__)

_API_BASE   = "https://api.kmanga.kodansha.com"
_VERSION    = "6.0.0"
_PLATFORM   = "3"

# Default birthday used before first login — taken from py-kapi defaults.
# Represents an anonymous/pre-auth session identity.
_DEFAULT_BIRTHDAY = json.dumps({"value": "2000-01", "expires": "4102444800"})

_DEFAULT_HEADERS = {
    "Accept":          "*/*",
    "Accept-Language": "en",
    "Connection":      "keep-alive",
    "DNT":             "1",
    "Referer":         "https://kmanga.kodansha.com/",
    "Origin":          "https://kmanga.kodansha.com/",
    "User-Agent":      "manga-tracker/1.0 Python/3 httpx",
}


# ── Hash generation ────────────────────────────────────────────────────────────

def _generate_xhash(params: dict[str, str], birthday_json: str) -> str:
    """
    Generate the x-kmanga-hash request signing header.
    Uses only stdlib hashlib — no pycryptodome required.
    """
    birthday = json.loads(birthday_json)
    parts: list[str] = []

    for key in sorted(params):
        key_hash = hashlib.sha256(key.encode("utf-8")).hexdigest()
        val_hash = hashlib.sha512(str(params[key]).encode("utf-8")).hexdigest()
        parts.append(f"{key_hash}_{val_hash}")

    param_digest = hashlib.sha256(",".join(parts).encode("utf-8")).hexdigest()

    bday_val  = hashlib.sha256(birthday["value"].encode("utf-8")).hexdigest()
    bday_exp  = hashlib.sha512(birthday["expires"].encode("utf-8")).hexdigest()
    bday_hash = f"{bday_val}_{bday_exp}"

    return hashlib.sha512((param_digest + bday_hash).encode("utf-8")).hexdigest()


# ── Exceptions ─────────────────────────────────────────────────────────────────

class KMangaError(Exception):
    pass

class KMangaAPIError(KMangaError):
    def __init__(self, code, message=""):
        self.code = code
        super().__init__(f"K Manga API error {code}: {message}")

class KMangaAuthError(KMangaAPIError):
    """Raised on authentication failure — caller should re-login."""
    pass

class KMangaNotFound(KMangaError):
    pass

class KMangaRegionError(KMangaError):
    """Raised when the server returns 403 / IP region block."""
    pass


# ── Client ─────────────────────────────────────────────────────────────────────

class KMangaClient:
    """
    Minimal K Manga API client for chapter-count tracking.

    Typical usage:
        client = KMangaClient(email, password, persisted_cookies)
        if not client.has_session():
            cookies = client.login()
            save_to_db(cookies)          # persist for next run

        title = client.get_title(title_id)
        count = title["total_episode_count"]
    """

    def __init__(
        self,
        email: str,
        password: str,
        cookies: dict[str, str] | None = None,
    ):
        self.email    = email
        self.password = password
        self.cookies: dict[str, str] = dict(cookies) if cookies else {}
        if "birthday" not in self.cookies:
            self.cookies["birthday"] = _DEFAULT_BIRTHDAY

    def has_session(self) -> bool:
        """True if we have a uwt session cookie (i.e. logged in)."""
        return bool(self.cookies.get("uwt"))

    # ── Low-level requests ────────────────────────────────────────────────────

    def _web_request(self, endpoint: str, params: dict) -> dict:
        """
        GET request for /web/* endpoints that use a different signing convention.

        Signing differences from _request():
          • Hash is computed from ONLY the business params (e.g. just title_id).
            version and platform are NOT included in the hash or query string.
          • Platform is sent as the x-kmanga-platform HEADER, not a query param.
          • x-kmanga-is-crawler header is added (value: "false").

        This matches the behaviour observed in K Manga's Nuxt JS bundle
        (e.g. getWebTitleDetail, getWebEpisode).
        """
        # Only business params go into hash/query — not version/platform
        str_params = {k: str(v) for k, v in params.items()}
        xhash = _generate_xhash(str_params, self.cookies["birthday"])
        headers = {
            **_DEFAULT_HEADERS,
            "x-kmanga-hash":        xhash,
            "x-kmanga-is-crawler":  "false",
            "x-kmanga-platform":    _PLATFORM,
        }
        url = _API_BASE + endpoint

        with httpx.Client(timeout=15, follow_redirects=True) as client:
            resp = client.get(url, params=str_params, headers=headers, cookies=self.cookies)

        if resp.status_code == 403:
            raise KMangaRegionError(
                "K Manga returned 403 — likely a US-only geographic restriction"
            )
        resp.raise_for_status()

        data = resp.json()
        for k, v in resp.cookies.items():
            self.cookies[k] = v

        if data.get("status") != "success":
            code = data.get("response_code", 0)
            msg  = data.get("error_message", "")
            if code in (2002, 1101, 1001):
                raise KMangaAuthError(code, msg)
            if code in (3104, 3100, 3000):
                raise KMangaNotFound(msg)
            raise KMangaAPIError(code, msg)

        return data

    def _request(self, method: str, endpoint: str, extra: dict | None = None) -> dict:
        payload: dict[str, str] = {
            "version":  _VERSION,
            "platform": _PLATFORM,
        }
        if extra:
            payload.update({k: str(v) for k, v in extra.items()})

        xhash   = _generate_xhash(payload, self.cookies["birthday"])
        headers = {**_DEFAULT_HEADERS, "x-kmanga-hash": xhash}
        url     = _API_BASE + endpoint

        with httpx.Client(timeout=15, follow_redirects=True) as client:
            if method == "GET":
                resp = client.get(
                    url, params=payload, headers=headers, cookies=self.cookies
                )
            else:
                resp = client.post(
                    url, data=payload, headers=headers, cookies=self.cookies
                )

        if resp.status_code == 403:
            raise KMangaRegionError(
                "K Manga returned 403 — likely a US-only geographic restriction"
            )
        resp.raise_for_status()

        data = resp.json()

        # Propagate updated cookies from response
        for k, v in resp.cookies.items():
            self.cookies[k] = v

        if data.get("status") != "success":
            code = data.get("response_code", 0)
            msg  = data.get("error_message", "")
            # Login-failure codes
            if code in (2002, 1101, 1001):
                raise KMangaAuthError(code, msg)
            if code in (3104, 3100, 3000):
                raise KMangaNotFound(msg)
            raise KMangaAPIError(code, msg)

        return data

    # ── Auth ──────────────────────────────────────────────────────────────────

    def login(self, recaptcha_token: str | None = None) -> dict[str, str]:
        """
        Authenticate with email/password. Updates internal cookies and
        returns the full cookie dict for the caller to persist.

        recaptcha_token:
          K Manga's web login endpoint now requires a reCAPTCHA v3 token.
          Without it the server returns code 1001 ("request parameter is invalid").
          When provided, this token is forwarded as the ``g-recaptcha-response``
          field.  If omitted the request is attempted anyway (it may still work
          if Kodansha relaxes the requirement or the token becomes optional on
          trusted IPs / mobile platforms).

          To obtain a valid token: in a browser visit https://kmanga.kodansha.com,
          open DevTools → Network, log in, and copy the ``g-recaptcha-response``
          POST parameter from the login request.  The token is short-lived (~2 min).

          Long-term: the Settings page exposes a ``kmanga_recaptcha_token`` field
          for manual input; the scheduler passes it automatically when present.
        """
        extra: dict = {"email": self.email, "password": self.password}
        if recaptcha_token:
            extra["g-recaptcha-response"] = recaptcha_token
        self._request("POST", "/web/user/login", extra)
        logger.info("K Manga: login successful")
        return dict(self.cookies)

    # ── Chapter tracking ─────────────────────────────────────────────────────

    def get_title_detail(self, title_id: int) -> dict:
        """
        Return web-tier title metadata via GET /web/title/detail.

        PREFERRED over get_title() for chapter tracking.  Does NOT require
        authentication — only the default birthday cookie is needed.

        Key fields from the response's "web_title" dict:
          episode_id_list     — ONE entry PER CHAPTER (not per sub-episode).
                                 episode_id_list[-1] is the latest chapter.
          total_episode_count — TRUE chapter count (e.g. 68, not 195).
          title_name          — English display title.

        Episode names returned by /web/episode for these IDs typically look like:
          "CHAPTER 68 HUNTING BUGS WITH A FEMALE KNIGHT"
          "CHAPTER 1 I FOUND A FEMALE KNIGHT IN MY PADDY"
        Note the ALL-CAPS format — parsers must be case-insensitive.
        """
        data = self._web_request("/web/title/detail", {"title_id": str(title_id)})
        wt = data.get("web_title")
        if not wt:
            raise KMangaNotFound(f"No web_title in response for id={title_id}")
        return wt

    def get_title(self, title_id: int) -> dict:
        """
        Return raw title metadata via GET /title/list.

        NOTE: Prefer get_title_detail() for chapter tracking.
        This endpoint returns ALL sub-episodes (e.g. 195 for a 68-chapter series)
        and its episode_id_list[-1] points to a sub-episode part, NOT a chapter.
        total_episode_count here counts sub-episodes, not chapters.

        Retained for compatibility / fallback use.
        """
        data   = self._request("GET", "/title/list", {"title_id_list": str(title_id)})
        titles = data.get("title_list", [])
        if not titles:
            raise KMangaNotFound(f"No title found for id={title_id}")
        return titles[0]

    def get_episode_name(self, episode_id: int) -> str | None:
        """
        Resolve an episode_id to its display name using GET /web/episode.

        This endpoint is more reliable for single-episode lookups than the
        POST /episode/list bulk endpoint.  Returns None if the episode is
        not accessible or not found.

        Typical return values:
          "Chapter 68 My Title Here"
          "Chapter 1.5 Side Story"
          "第68話 タイトル"
        """
        try:
            data = self._web_request("/web/episode", {"episode_id": str(episode_id)})
            ep   = data.get("episode", {})
            return ep.get("episode_name") or None
        except (KMangaNotFound, KMangaAPIError):
            return None

    def get_latest_episode_id(self, title_data: dict) -> int | None:
        """
        Determine the best episode ID to use for chapter-name resolution.

        Priority:
          1. Last element of episode_id_list  — the absolute newest episode
             regardless of paid/free status (most accurate).
          2. Last element of latest_paid_episode_id (list) — if episode_id_list
             is absent.
          3. latest_free_episode_id (integer) — last resort.

        Returns None if no episode ID can be determined.
        """
        ep_id_list = title_data.get("episode_id_list") or []
        if ep_id_list:
            return ep_id_list[-1]

        paid_ids = title_data.get("latest_paid_episode_id") or []
        if paid_ids:
            return paid_ids[-1]

        free_id = title_data.get("latest_free_episode_id")
        return int(free_id) if free_id else None

    def scan_latest_chapter(
        self,
        title_id: int,
        scan_window: int = 5,
    ) -> tuple[str | None, str | None]:
        """
        Return the latest chapter number and raw episode name for a title.

        PRIMARY PATH — /web/title/detail (no auth required):
          This endpoint returns one episode ID per CHAPTER (not per sub-episode).
          episode_id_list[-1] is the latest chapter's representative episode.
          Example: 68-chapter series → 68 items, last = episode 363822
                   = "CHAPTER 68 HUNTING BUGS WITH A FEMALE KNIGHT"

        FALLBACK — scan window from /title/list data:
          If /web/title/detail is unavailable (paywall, error), falls back to
          scanning the last *scan_window* sub-episodes from a pre-fetched
          title_data dict (from get_title()), preferring canonical "Chapter N"
          names to avoid misparses.

        Returns (chapter_str | None, raw_episode_name | None).
        """
        # ── Primary: /web/title/detail (no auth, chapter-level list) ──────────
        try:
            wt = self.get_title_detail(title_id)
            ep_id_list = wt.get("episode_id_list") or []
            if ep_id_list:
                latest_ep_id = ep_id_list[-1]
                ep_name = self.get_episode_name(int(latest_ep_id))
                if ep_name:
                    chapter = parse_chapter_from_episode_name(ep_name)
                    if chapter is not None:
                        logger.debug(
                            f"K Manga: /web/title/detail ep={latest_ep_id} "
                            f"name={ep_name!r} → chapter={chapter!r}"
                        )
                        return chapter, ep_name
                    # Couldn't parse from primary — scan last few for backup
                    logger.debug(
                        f"K Manga: /web/title/detail last ep name unparseable: "
                        f"{ep_name!r} — scanning {scan_window} more episodes"
                    )
                    for ep_id in reversed(ep_id_list[-(scan_window + 1):-1]):
                        name = self.get_episode_name(int(ep_id))
                        if name:
                            ch = parse_chapter_from_episode_name(name)
                            if ch is not None:
                                return ch, name
        except (KMangaNotFound, KMangaAPIError) as e:
            logger.debug(f"K Manga: /web/title/detail failed ({e}), using fallback scan")
        except Exception as e:
            logger.warning(f"K Manga: /web/title/detail unexpected error ({e}), using fallback scan")

        # ── Fallback: scan window from authenticated /title/list data ──────────
        # Caller must pre-fetch title_data via get_title() and pass title_id so
        # we can still make the episode name requests.
        # This path is only taken if the primary fails.
        logger.debug(
            f"K Manga: falling back to /title/list scan for title_id={title_id}"
        )
        try:
            title_data = self.get_title(title_id)
        except Exception as e:
            logger.warning(f"K Manga: get_title fallback also failed: {e}")
            return None, None

        ep_id_list = title_data.get("episode_id_list") or []
        if not ep_id_list:
            ep_id = self.get_latest_episode_id(title_data)
            if not ep_id:
                return None, None
            ep_name = self.get_episode_name(int(ep_id))
            return parse_chapter_from_episode_name(ep_name), ep_name

        tail = list(reversed(ep_id_list[-scan_window:]))
        best_chapter: str | None = None
        best_name:    str | None = None

        for ep_id in tail:
            ep_name = self.get_episode_name(int(ep_id))
            if not ep_name:
                continue
            canonical = _parse_chapter_canonical(ep_name)
            if canonical is not None:
                if best_chapter is None or float(canonical) > float(best_chapter):
                    best_chapter = canonical
                    best_name    = ep_name

        if best_chapter is not None:
            return best_chapter, best_name

        # Last resort: first number from the newest episode
        if tail:
            ep_name = self.get_episode_name(int(tail[0]))
            if ep_name:
                return parse_chapter_from_episode_name(ep_name), ep_name

        return None, None

    def get_updated_titles(self, base_date: str | None = None) -> list[dict]:
        """
        Return titles updated since base_date (YYYY-MM-DD string).
        One call covers all K Manga content — equivalent to MU's /releases/days.
        Each item contains: title_id, title_name, latest_free_episode_id.
        """
        extra = {}
        if base_date:
            extra["base_date"] = base_date
        return self._request("GET", "/web/top/updated/title", extra).get("title_list", [])


# ── Chapter number helpers ─────────────────────────────────────────────────────

def _parse_chapter_canonical(episode_name: str) -> str | None:
    """
    Strict canonical chapter extraction — only matches unambiguous patterns.

    Accepts:
      • "Chapter N" / "CHAPTER N" / "Ch. N" / "CH. N" / "Chap. N" (case-insensitive)
      • "第N話" / "第N回" (Japanese)

    Deliberately rejects bare numbers and any other heuristic matches.
    Used by scan_latest_chapter() when we need high confidence that the number
    really is the chapter number, not a volume number or campaign counter.

    K Manga's /web/episode endpoint returns episode names in ALL-CAPS:
      "CHAPTER 68 HUNTING BUGS WITH A FEMALE KNIGHT"
    so case-insensitive matching is required here.

    Returns the chapter number as a string ("68", "1.5"), or None.
    """
    if not episode_name:
        return None

    def _fmt(m: re.Match) -> str:
        val = float(m.group(1))
        return str(int(val)) if val == int(val) else str(val)

    # English "Chapter" / "Ch." / "Chap." prefix — case-insensitive
    m = re.search(r'[Cc][Hh](?:[Aa][Pp][Tt][Ee][Rr]|[Aa][Pp]\.?|\.?)\s*(\d+(?:\.\d+)?)', episode_name)
    if m:
        return _fmt(m)

    # Japanese 第N話 / 第N回
    m = re.search(r'第\s*(\d+(?:\.\d+)?)\s*[話回]', episode_name)
    if m:
        return _fmt(m)

    return None


def parse_chapter_from_episode_name(episode_name: str) -> str | None:
    """
    Extract a chapter number from a K Manga episode name string.

    Tries patterns in priority order so that episode-counter numbers
    embedded in series titles (e.g. "Season 2 Chapter 3") don't shadow
    the real chapter number:

      1. "Chapter N" / "chapter N" / "Chap. N" / "Ch. N" / "Ch N"
         → e.g.  "Chapter 68 My Title Here"      → "68"
                 "Ch. 1.5 Side Story"              → "1.5"
      2. Japanese "第N話" or "第N回"
         → e.g.  "第68話"                         → "68"
      3. Generic first number in the string (last resort, may be wrong
         for titles with numbers in the subtitle)
         → e.g.  "68"                             → "68"

    Returns the chapter number as a string ("68", "1.5"), or None if
    nothing parseable is found.
    """
    if not episode_name:
        return None

    def _fmt(m: re.Match) -> str:
        val = float(m.group(1))
        return str(int(val)) if val == int(val) else str(val)

    # Priority 1 — English "Chapter" / "Ch." prefix (case-insensitive for K Manga's ALL-CAPS)
    m = re.search(r'[Cc][Hh](?:[Aa][Pp][Tt][Ee][Rr]|[Aa][Pp]\.?|\.?)\s*(\d+(?:\.\d+)?)', episode_name)
    if m:
        return _fmt(m)

    # Priority 2 — Japanese 第N話 / 第N回
    m = re.search(r'第\s*(\d+(?:\.\d+)?)\s*[話回]', episode_name)
    if m:
        return _fmt(m)

    # Priority 3 — any leading bare number (e.g. "68 - Title Here")
    m = re.match(r'(\d+(?:\.\d+)?)\s*[-–—\s]', episode_name)
    if m:
        return _fmt(m)

    # Last resort — first number anywhere in the string
    m = re.search(r'(\d+(?:\.\d+)?)', episode_name)
    if m:
        return _fmt(m)

    return None
