"""
K Manga (Kodansha) API client — chapter tracking only.

API base:  https://api.kmanga.kodansha.com
Auth:      Session cookies (birthday + uwt) obtained via POST /web/user/login.
           Every request requires an x-kmanga-hash header generated by signing
           the full request parameter dict with the birthday cookie value.
           Geographic restriction: US IPs only (403 otherwise).

Title IDs: The integer in the K Manga URL:
           https://kmanga.kodansha.com/title/{title_id}

x-kmanga-hash algorithm (reverse-engineered from py-kapi/pykapi/kapi.py):
  For each param key sorted alphabetically:
    part = SHA256(key) + "_" + SHA512(str(value))
  joined = ",".join(all parts)
  param_digest = SHA256(joined)
  birthday_dict = JSON.parse(birthday_cookie)
  birthday_hash = SHA256(birthday_dict["value"]) + "_" + SHA512(birthday_dict["expires"])
  final_hash = SHA512(param_digest + birthday_hash)

Session management:
  - On first use (or when uwt cookie is absent), call login() to authenticate.
  - Cookies (birthday + uwt) are returned from login() as a dict for the caller
    to persist in the settings DB.
  - Pass persisted cookies back into the constructor on subsequent app starts
    to avoid re-logging in on every poll.
  - If a request fails with KMangaAuthError, caller should re-login.
"""
import hashlib
import json
import logging
import re

import httpx

logger = logging.getLogger(__name__)

_API_BASE   = "https://api.kmanga.kodansha.com"
_VERSION    = "6.0.0"
_PLATFORM   = "3"

# Default birthday used before first login — taken from py-kapi defaults.
# Represents an anonymous/pre-auth session identity.
_DEFAULT_BIRTHDAY = json.dumps({"value": "2000-01", "expires": "4102444800"})

_DEFAULT_HEADERS = {
    "Accept":          "*/*",
    "Accept-Language": "en",
    "Connection":      "keep-alive",
    "DNT":             "1",
    "Referer":         "https://kmanga.kodansha.com/",
    "Origin":          "https://kmanga.kodansha.com/",
    "User-Agent":      "manga-tracker/1.0 Python/3 httpx",
}


# ── Hash generation ────────────────────────────────────────────────────────────

def _generate_xhash(params: dict[str, str], birthday_json: str) -> str:
    """
    Generate the x-kmanga-hash request signing header.
    Uses only stdlib hashlib — no pycryptodome required.
    """
    birthday = json.loads(birthday_json)
    parts: list[str] = []

    for key in sorted(params):
        key_hash = hashlib.sha256(key.encode("utf-8")).hexdigest()
        val_hash = hashlib.sha512(str(params[key]).encode("utf-8")).hexdigest()
        parts.append(f"{key_hash}_{val_hash}")

    param_digest = hashlib.sha256(",".join(parts).encode("utf-8")).hexdigest()

    bday_val  = hashlib.sha256(birthday["value"].encode("utf-8")).hexdigest()
    bday_exp  = hashlib.sha512(birthday["expires"].encode("utf-8")).hexdigest()
    bday_hash = f"{bday_val}_{bday_exp}"

    return hashlib.sha512((param_digest + bday_hash).encode("utf-8")).hexdigest()


# ── Exceptions ─────────────────────────────────────────────────────────────────

class KMangaError(Exception):
    pass

class KMangaAPIError(KMangaError):
    def __init__(self, code, message=""):
        self.code = code
        super().__init__(f"K Manga API error {code}: {message}")

class KMangaAuthError(KMangaAPIError):
    """Raised on authentication failure — caller should re-login."""
    pass

class KMangaNotFound(KMangaError):
    pass

class KMangaRegionError(KMangaError):
    """Raised when the server returns 403 / IP region block."""
    pass


# ── Client ─────────────────────────────────────────────────────────────────────

class KMangaClient:
    """
    Minimal K Manga API client for chapter-count tracking.

    Typical usage:
        client = KMangaClient(email, password, persisted_cookies)
        if not client.has_session():
            cookies = client.login()
            save_to_db(cookies)          # persist for next run

        title = client.get_title(title_id)
        count = title["total_episode_count"]
    """

    def __init__(
        self,
        email: str,
        password: str,
        cookies: dict[str, str] | None = None,
    ):
        self.email    = email
        self.password = password
        self.cookies: dict[str, str] = dict(cookies) if cookies else {}
        if "birthday" not in self.cookies:
            self.cookies["birthday"] = _DEFAULT_BIRTHDAY

    def has_session(self) -> bool:
        """True if we have a uwt session cookie (i.e. logged in)."""
        return bool(self.cookies.get("uwt"))

    # ── Low-level request ─────────────────────────────────────────────────────

    def _request(self, method: str, endpoint: str, extra: dict | None = None) -> dict:
        payload: dict[str, str] = {
            "version":  _VERSION,
            "platform": _PLATFORM,
        }
        if extra:
            payload.update({k: str(v) for k, v in extra.items()})

        xhash   = _generate_xhash(payload, self.cookies["birthday"])
        headers = {**_DEFAULT_HEADERS, "x-kmanga-hash": xhash}
        url     = _API_BASE + endpoint

        with httpx.Client(timeout=15, follow_redirects=True) as client:
            if method == "GET":
                resp = client.get(
                    url, params=payload, headers=headers, cookies=self.cookies
                )
            else:
                resp = client.post(
                    url, data=payload, headers=headers, cookies=self.cookies
                )

        if resp.status_code == 403:
            raise KMangaRegionError(
                "K Manga returned 403 — likely a US-only geographic restriction"
            )
        resp.raise_for_status()

        data = resp.json()

        # Propagate updated cookies from response
        for k, v in resp.cookies.items():
            self.cookies[k] = v

        if data.get("status") != "success":
            code = data.get("response_code", 0)
            msg  = data.get("error_message", "")
            # Login-failure codes
            if code in (2002, 1101, 1001):
                raise KMangaAuthError(code, msg)
            if code in (3104, 3100, 3000):
                raise KMangaNotFound(msg)
            raise KMangaAPIError(code, msg)

        return data

    # ── Auth ──────────────────────────────────────────────────────────────────

    def login(self) -> dict[str, str]:
        """
        Authenticate with email/password. Updates internal cookies and
        returns the full cookie dict for the caller to persist.
        """
        self._request("POST", "/web/user/login", {
            "email":    self.email,
            "password": self.password,
        })
        logger.info("K Manga: login successful")
        return dict(self.cookies)

    # ── Chapter tracking ─────────────────────────────────────────────────────

    def get_title(self, title_id: int) -> dict:
        """
        Return title metadata for a single title_id.
        Key fields:
          total_episode_count   — total chapters published
          latest_free_episode_id — episode ID of the newest free chapter
          episode_free_updated  — ISO-ish date of last free episode update
          episode_paid_updated  — ISO-ish date of last paid episode update
        """
        data   = self._request("GET", "/title/list", {"title_id_list": str(title_id)})
        titles = data.get("title_list", [])
        if not titles:
            raise KMangaNotFound(f"No title found for id={title_id}")
        return titles[0]

    def get_episode_name(self, episode_id: int) -> str | None:
        """
        Resolve an episode_id to its display name (e.g. "Ch. 68", "第68話").
        Returns None if the episode is not accessible or not found.
        """
        try:
            data     = self._request("POST", "/episode/list", {"episode_id_list": str(episode_id)})
            episodes = data.get("episode_list", [])
            return episodes[0].get("episode_name") if episodes else None
        except (KMangaNotFound, KMangaAPIError):
            return None

    def get_updated_titles(self, base_date: str | None = None) -> list[dict]:
        """
        Return titles updated since base_date (YYYY-MM-DD string).
        One call covers all K Manga content — equivalent to MU's /releases/days.
        Each item contains: title_id, title_name, latest_free_episode_id.
        """
        extra = {}
        if base_date:
            extra["base_date"] = base_date
        return self._request("GET", "/web/top/updated/title", extra).get("title_list", [])


# ── Chapter number helpers ─────────────────────────────────────────────────────

def parse_chapter_from_episode_name(episode_name: str) -> str | None:
    """
    Extract a numeric chapter identifier from a K Manga episode name string.
    Handles:  "Ch. 68"  |  "Chapter 68"  |  "第68話"  |  "68"  |  "68.5"
    Returns the number as a string, or None if no number is found.
    """
    if not episode_name:
        return None
    m = re.search(r"(\d+(?:\.\d+)?)", episode_name)
    if not m:
        return None
    val = float(m.group(1))
    return str(int(val)) if val == int(val) else str(val)
